In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

2.4.6


In [3]:
## Create Numpy Array
salary = [50000,60000,70000]
print(salary)

[50000, 60000, 70000]


In [2]:
import numpy as np 

salary = np.array(
    [50000, 60000, 70000]
)

print(salary)

salary = salary * 1.10

print(salary)

[50000 60000 70000]
[55000. 66000. 77000.]


In [3]:
## Exercise 1
sales = np.array(
[1000,2000,3000,4000]
)

sales = sales * 1.18

print(sales)

[1180. 2360. 3540. 4720.]


In [6]:
data = np.array(
[
[1,2,3],
[4,5,6]
]
)

print(data.shape)
print(data.ndim)
print(data.size)

(2, 3)
2
6


In [8]:
salary=np.array(
[30000,50000,80000]
)


print(salary[0])
print(salary[-1])

30000
80000


In [10]:
high_salary = salary[salary >= 50000]

print(high_salary)

[50000 80000]


In [13]:
## Exercise 2
marks=np.array(
[45,80,35,90,60]
)

output_marks = marks[marks >= 60]
print(output_marks)

[80 90 60]


In [14]:
## Aggregations

salary=np.array(
[30000,50000,80000]
)

print(np.max(salary))

print(np.min(salary))

print(np.mean(salary))

print(np.sum(salary))

80000
30000
53333.333333333336
160000


In [16]:
## Exercise 3
orders=np.array(
[200,500,700,100]
)

print(np.sum(orders))
print(np.mean(orders))
print(np.max(orders))

1500
375.0
700


In [19]:
data=np.array(
[
100,
200,
np.nan,
400
]
)

print(np.mean(data))
print(np.nanmean(data))

nan
233.33333333333334


In [22]:
## Exercise 4
salary=np.array(
[
50000,
np.nan,
70000,
90000
]
)

print(np.nanmean(salary))

70000.0


In [23]:
## Where 
salary=np.array(
[30000,80000,40000]
)

result = np.where(salary > 50000,"High","Low")
print(result)


['Low' 'High' 'Low']


In [24]:
## Exercise 5
marks=np.array(
[40,70,90]
)

result = np.where(marks>=50,"Pass","Fail")
print(result)

['Fail' 'Pass' 'Pass']


In [27]:
salary=np.array(
[
30000,
50000,
80000,
100000
]
)

salary = salary * 1.10
output_salary = salary[salary>60000]

print(output_salary)
print(np.nanmean(output_salary))
position = np.where(salary>=70000,"Senior","Junior")
print(position)

[ 88000. 110000.]
99000.0
['Junior' 'Junior' 'Senior' 'Senior']
